version: '3'

services:
 
  Scraper:
    image: buho/scraper
    command: 'gunicorn -w 4 -b 0.0.0.0:8000 app:app'
    volumes:
      - .:/prototipo-scrapper
    environment:
      VIRTUAL_HOST: 'prototipo-scraper.buho.media'
      C_FORCE_ROOT: 1
      LC_ALL: 'C.UTF-8'
      LANG: 'C.UTF-8'
      TZ: 'America/Bogota'
      VIRTUAL_PORT: '5050'
      LETSENCRYPT_HOST: 'prototipo-scraper.buho.media'
      LETSENCRYPT_EMAIL: 'sistemas@buho.media'
    networks:
        - default
        - nginx_proxy

networks:
  default:
  nginx_proxy:
    external: true

